# Generated by Django 3.1.2 on 2020-11-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0003_auto_20201106_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
