# Generated by Django 3.1.2 on 2020-11-26 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QnA', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_likes',
            field=models.ManyToManyField(blank=True, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
