# Generated by Django 3.1.2 on 2020-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnA', '0010_auto_20201127_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
